[package]
name = "prime-gaps"
version = "1.0.0"
authors = ["Jeffrey Stanton <jffry@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.4.3"
primal = "0.3.2"
